package com.example.demo.service.product.serviceImpl;

import com.example.demo.config.CacheConfig;
import com.example.demo.dto.patch.product.CustomerPatchRequest;
import com.example.demo.dto.request.product.CustomerRequest;
import com.example.demo.dto.response.product.CustomerResponse;
import com.example.demo.entity.product.Customer;
import com.example.demo.entity.product.Email;
import com.example.demo.exception.ResourceNotFoundException;
import com.example.demo.repository.product.CustomerRepository;
import com.example.demo.repository.product.EmailRepository;
import com.example.demo.service.product.CustomerService;
import org.modelmapper.ModelMapper;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class CustomerServiceImpl implements CustomerService {

    private final CustomerRepository customerRepository;
    private final EmailRepository emailRepository;
    private final ModelMapper modelMapper;

    public CustomerServiceImpl(CustomerRepository customerRepository, EmailRepository emailRepository, ModelMapper modelMapper) {
        this.customerRepository = customerRepository;
        this.emailRepository = emailRepository;
        this.modelMapper = modelMapper;
    }

    @Override
    public Page<CustomerResponse> getAll(Pageable pageable) {
        return customerRepository.findAll(pageable)
                .map(this::toResponse);
    }

    @Override
    @Cacheable(value = CacheConfig.CACHE_CUSTOMERS, key = "#id")
    public CustomerResponse getById(Long id) {
        return toResponse(findCustomerById(id));
    }

    @Override
    public CustomerResponse create(CustomerRequest request) {
        Email email;
        if (request.emailId() != null) {
            email = findEmailById(request.emailId());
            if (customerRepository.existsByEmailId(request.emailId())) {
                throw new IllegalArgumentException("Email with id " + request.emailId() + " is already linked to another customer.");
            }
        } else {
            email = createAutoGeneratedEmail(request.customerName());
        }

        Customer customer = new Customer();
        customer.setCustomerName(request.customerName());
        customer.setAddress(request.address());
        customer.setPhoneNumber(request.phoneNumber());
        customer.setEmail(email);

        return toResponse(customerRepository.save(customer));
    }

    @Override
    @CacheEvict(value = CacheConfig.CACHE_CUSTOMERS, key = "#id")
    public CustomerResponse update(Long id, CustomerRequest request) {
        Customer existingCustomer = findCustomerById(id);

        Email email;
        if (request.emailId() != null) {
            email = findEmailById(request.emailId());
            if (customerRepository.existsByEmailIdAndIdNot(request.emailId(), id)) {
                throw new IllegalArgumentException("Email with id " + request.emailId() + " is already linked to another customer.");
            }
        } else if (existingCustomer.getEmail() != null) {
            email = existingCustomer.getEmail();
        } else {
            email = createAutoGeneratedEmail(request.customerName());
        }

        existingCustomer.setCustomerName(request.customerName());
        existingCustomer.setAddress(request.address());
        existingCustomer.setPhoneNumber(request.phoneNumber());
        existingCustomer.setEmail(email);

        return toResponse(customerRepository.save(existingCustomer));
    }

    @Override
    @CacheEvict(value = CacheConfig.CACHE_CUSTOMERS, key = "#id")
    public CustomerResponse edit(Long id, CustomerPatchRequest request) {
        Customer existingCustomer = findCustomerById(id);

        if (request.customerName() != null) {
            existingCustomer.setCustomerName(request.customerName());
        }
        if (request.address() != null) {
            existingCustomer.setAddress(request.address());
        }
        if (request.phoneNumber() != null) {
            existingCustomer.setPhoneNumber(request.phoneNumber());
        }

        if (Boolean.TRUE.equals(request.unlinkEmail())) {
            existingCustomer.setEmail(null);
        } else if (request.emailId() != null) {
            Email email = findEmailById(request.emailId());
            if (customerRepository.existsByEmailIdAndIdNot(request.emailId(), id)) {
                throw new IllegalArgumentException("Email with id " + request.emailId() + " is already linked to another customer.");
            }
            existingCustomer.setEmail(email);
        }

        return toResponse(customerRepository.save(existingCustomer));
    }

    @Override
    @CacheEvict(value = CacheConfig.CACHE_CUSTOMERS, key = "#id")
    public void deleteById(Long id) {
        customerRepository.delete(findCustomerById(id));
    }

    @Override
    public Page<CustomerResponse> search(String name, String phone, Pageable pageable) {
        if (phone != null && !phone.isBlank()) {
            phone = com.example.demo.util.PhoneNumberUtils.formatPhoneNumber(phone);
        }
        return customerRepository.searchCustomers(name, phone, pageable)
                .map(this::toResponse);
    }

    private Customer findCustomerById(Long id) {
        return customerRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Customer not found with id: " + id));
    }

    private Email findEmailById(Long id) {
        return emailRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Email not found with id: " + id));
    }

    private Email createAutoGeneratedEmail(String customerName) {
        String baseName = customerName != null ? customerName.trim().toLowerCase().replaceAll("\\s+", "") : "customer";
        if (baseName.isEmpty()) {
            baseName = "customer";
        }
        String generatedEmailStr = baseName + "@store.com";
        int counter = 1;
        while (emailRepository.existsByEmail(generatedEmailStr)) {
            generatedEmailStr = baseName + counter + "@store.com";
            counter++;
        }

        Email newEmail = new Email();
        newEmail.setEmail(generatedEmailStr);
        return emailRepository.save(newEmail);
    }

    public CustomerResponse toResponse(Customer customer) {
        if (customer == null) {
            return null;
        }
        CustomerResponse response = modelMapper.map(customer, CustomerResponse.class);
        response.setPhoneNumber(com.example.demo.util.PhoneNumberUtils.formatPhoneNumber(customer.getPhoneNumber()));
        if (customer.getEmail() != null) {
            response.setEmailId(customer.getEmail().getId());
            response.setEmail(customer.getEmail().getEmail());
        }
        return response;
    }
}
